services:
  tender-db:
    image: postgres:16.1
    container_name: TenderDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tender
      - POSTGRES_USER=tender
      - POSTGRES_PASSWORD=tender
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10