spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tender
    username: tender
    password: tender
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Предотвращение проблем с lazy loading
        enable_lazy_load_no_trans: false
        # Ограничение глубины загрузки
        max_fetch_depth: 3
        # Отключение автоматической загрузки связанных сущностей
        default_batch_fetch_size: 16
        # Настройки для предотвращения N+1 проблем
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        # Настройки кэширования
        cache:
          use_second_level_cache: false
          use_query_cache: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:false}
    default-encoding: UTF-8

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # Настройки для предотвращения таймаутов
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 100

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    # Добавляем логирование для отладки проблем
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    ru.perminov.tender: DEBUG

# Notification settings
notification:
  email:
    enabled: true
    from: ${MAIL_USERNAME:your-email@gmail.com}
    templates:
      tender-published: "tender-published"
      tender-reminder: "tender-reminder"
      proposal-submitted: "proposal-submitted"
      tender-awarded: "tender-awarded"
      tender-cancelled: "tender-cancelled"

# JWT settings
jwt:
  secret: ${JWT_SECRET:iuLTU8rq83ssfe4gfege5ge5hryjtyumjt7mt7mh6iu}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds